/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutFeedIdIndexRouteImport } from './routes/_layout/$feedId/index'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutFeedIdItemIdRouteImport } from './routes/_layout/$feedId/$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFeedIdIndexRoute = LayoutFeedIdIndexRouteImport.update({
  id: '/$feedId/',
  path: '/$feedId/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutFeedIdItemIdRoute = LayoutFeedIdItemIdRouteImport.update({
  id: '/$feedId/$itemId',
  path: '/$feedId/$itemId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/$feedId': typeof LayoutFeedIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/$feedId': typeof LayoutFeedIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/_layout/$feedId/': typeof LayoutFeedIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/$feedId/$itemId' | '/dashboard' | '/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/$feedId/$itemId' | '/dashboard' | '/$feedId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/_authenticated'
    | '/_layout/'
    | '/_layout/$feedId/$itemId'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/$feedId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$feedId/': {
      id: '/_layout/$feedId/'
      path: '/$feedId'
      fullPath: '/$feedId'
      preLoaderRoute: typeof LayoutFeedIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/$feedId/$itemId': {
      id: '/_layout/$feedId/$itemId'
      path: '/$feedId/$itemId'
      fullPath: '/$feedId/$itemId'
      preLoaderRoute: typeof LayoutFeedIdItemIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute: LayoutAuthenticatedDashboardRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFeedIdItemIdRoute: typeof LayoutFeedIdItemIdRoute
  LayoutFeedIdIndexRoute: typeof LayoutFeedIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFeedIdItemIdRoute: LayoutFeedIdItemIdRoute,
  LayoutFeedIdIndexRoute: LayoutFeedIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
